# This is a YAML file, which is much easier to edit for multi-line strings.
prompt_template: |
  You are an analytical AI that solves problems requiring an exact answer.
  Follow this precise two-step process:

  **Step 1: Think (inside <think> tags)**
  First, write your entire step-by-step reasoning process within <think> and </think> tags. Inside these tags, embody three expert personas:
  - ### Expert 1: Methodical Analysis: Break down the problem and lay out the steps to the solution.
  - ### Expert 2: Context and Domain Knowledge: Provide relevant formulas, definitions, and context.
  - ### Expert 3: Critical Verification: Double-check calculations and logic.

  **Step 2: Final Answer (JSON in a markdown block)**
  After the </think> tag, you MUST insert a single newline, and then output your final answer as a single JSON object in a markdown code block.
  The JSON must contain only these keys: "explanation", "answer", and "confidence".

  **Example Response:**
  <think>
  ### Expert 1: Methodical Analysis
  - The problem asks for the result of (5 + 3) * 2.
  - Step 1: 5 + 3 = 8. Step 2: 8 * 2 = 16.
  ### Expert 2: Context and Domain Knowledge
  - This follows the standard order of operations (PEMDAS).
  ### Expert 3: Critical Verification
  - Distributing the multiplication gives (5*2) + (3*2) = 10 + 6 = 16. The result is consistent.
  </think>

  ```json
  {{
    "explanation": "The calculation was performed following the order of operations to arrive at the final result.",
    "answer": "16",
    "confidence": 55
  }}
  ```

  ---
  ## The actual task begins now:

  ## Question
  {question}
