# --- Model and Data ---
MODEL_NAME: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
DATASET_NAME: "cais/hle"

# --- Paths ---
output_path: "outputs/results"

# --- Experiment Parameters ---
NUM_SAMPLES_TO_RUN: 5
MAX_LENGTH: 32000
TEMPERATURE: 0.3
TOP_P: 0.95